// ===========================================================
// CATÁLOGOS / MAESTROS
// ===========================================================

Table MODELO {
  modelo_id int [pk]
  modelo_desc varchar(50) [unique]
}

Table MARCA {
  marca_id int [pk]
  marca_desc varchar(50) [unique]
  modelo_id int
}

Table TIPO_EQUIPO {
  tipo_equipo_id int [pk]
  tipo_equipo_desc varchar(50) [unique]
}

Table EQUIPO {
  equipo_id int [pk]
  equipo_desc varchar(50) [unique]
  tipo_equipo_id int
  marca_id int
}

Table FAENA {
  faena_id int [pk]
  faena_desc varchar(50) [unique]
}

Table PROVEEDOR {
  proveedor_id int [pk]
  proveedor_desc varchar(50) [unique]
}

Table CUENTA {
  cuenta_id int [pk]
  cuenta_desc varchar(50) [unique]
}

Table CENTRO_COSTO {
  centro_costo_id int [pk]
  centro_costo_desc varchar(50) [unique]
  cuenta_id int
}

Table MOTIVO_COMPRA {
  motvo_compra_id int [pk]
  motvo_compra_desc varchar(50) [unique]
}

Table ITEM {
  item_id int [pk]
  item_desc varchar(50) [unique]
}

Table SISTEMA {
  sistema_id int [pk]
  sistema_reparacion_desc varchar(50) [unique]
}

Table SINTOMA {
  sintoma_id int [pk]
  sintoma_reparacion_desc varchar(50) [unique]
}

Table MOTIVO_REPARACION {
  mo_reparacion_id int [pk]
  mo_reparacion_desc varchar(50) [unique]
}


// ===========================================================
// COMPRAS / PROGRAMA / MANTENIMIENTO
// ===========================================================

Table ORDEN_COMPRA {
  oc_id int [pk]
  oc_desc varchar(50)
  motvo_compra_id int
  item_id int
  proveedor_id int
  centro_costo_id int
  oc_item_cantidad int
  oc_item_unidad varchar(30)
  oc_item_monto_total decimal(8,0)
  oc_monto_neto decimal(8,0)
  oc_valor_total decimal(8,0)
  oc_monto_total_factura decimal(8,0)
  oc_fecha_emision_factura date
  otm_id int 
}

Table PROGRAMA {
  programa_id int [pk]
  faena_id int
  equipo_id int
  horometro_referencia decimal(5,0)
  disponibilidad_insumos varchar(50)
  usuario_programacion varchar(50)
  estado_otm varchar(50)
}

Table NOTIFICACION {
  notificacion_id int [pk]
  notificacion_desc varchar(50)
  notificacion_fec date
  equipo_id int
  mo_reparacion_id int
  faena_id int
  sistema_id int
  sintoma_id int
}



Table ORDEN_MAN {
  otm_id int [pk]
  otm_desc varchar(50)
  solicitud_id int
  programa_id int
}

Table ORDEN_REP {
  otr_id int [pk]
  otr_desc varchar(50)
  notificacion_id integer
}


// ===========================================================
// REPROGRAMACIONES
// ===========================================================

Table MOTIVO_REPROGRAMACION {
  motivo_reprogramacion_id int [pk]
  motivo_reprogramacion_desc varchar(100) [unique]
}

Table REPROGRAMACION_OTM {
  n_reprogramacion int [pk]
  otm_id int [pk]
  fecha_inicio date
  motivo_reprogramacion_id int
}


// ===========================================================
// TIEMPOS DE BAJA
// ===========================================================

Table TIEMPO_BAJA {
  equipo_id int [pk]
  fecha_inicio date [pk]
  turno boolean
}


// ===========================================================
// PRÓXIMO MANTENIMIENTO
// ===========================================================

Table PROXIMO_MANTENIMIENTO {
  equipo_id int [pk]
  ultimo_horometro_otm numeric(8,0)
  fec_ultima_otm date
  prom_horas_entre_otm numeric(5,0)
  prom_horas_trabajadas_diarias numeric(5,0)
  dias_restantes numeric(3,1)
  fecha_prox_otm date
  horometro_prox_otm numeric(7,0)
}


// ===========================================================
// RELACIONES
// ===========================================================

// Catálogos
Ref: MARCA.modelo_id> MODELO.modelo_id
Ref: EQUIPO.tipo_equipo_id > TIPO_EQUIPO.tipo_equipo_id
Ref: EQUIPO.marca_id > MARCA.marca_id
Ref: CENTRO_COSTO.cuenta_id > CUENTA.cuenta_id

// Compras / Programa
Ref: ORDEN_COMPRA.motvo_compra_id > MOTIVO_COMPRA.motvo_compra_id
Ref: ORDEN_COMPRA.item_id > ITEM.item_id
Ref: ORDEN_COMPRA.proveedor_id > PROVEEDOR.proveedor_id
Ref: ORDEN_COMPRA.centro_costo_id > CENTRO_COSTO.centro_costo_id
Ref: PROGRAMA.equipo_id > EQUIPO.equipo_id
Ref: PROGRAMA.faena_id > FAENA.faena_id
Ref: ORDEN_COMPRA.otm_id  > ORDEN_MAN.otm_id

// Notificaciones / Solicitudes / Órdenes
Ref: NOTIFICACION.equipo_id > EQUIPO.equipo_id
Ref: NOTIFICACION.mo_reparacion_id > MOTIVO_REPARACION.mo_reparacion_id
Ref: NOTIFICACION.faena_id > FAENA.faena_id
Ref: NOTIFICACION.sistema_id > SISTEMA.sistema_id
Ref: NOTIFICACION.sintoma_id > SINTOMA.sintoma_id
Ref: ORDEN_MAN.programa_id > PROGRAMA.programa_id
Ref: ORDEN_REP.notificacion_id > NOTIFICACION.notificacion_id

// Reprogramaciones
Ref: REPROGRAMACION_OTM.otm_id > ORDEN_MAN.otm_id
Ref: REPROGRAMACION_OTM.motivo_reprogramacion_id > MOTIVO_REPROGRAMACION.motivo_reprogramacion_id

// Tiempo de baja
Ref: TIEMPO_BAJA.equipo_id > EQUIPO.equipo_id

// Próximo mantenimiento
Ref: PROXIMO_MANTENIMIENTO.equipo_id > EQUIPO.equipo_id

